In [8]:
import pandas as pd

# Veri setini oku
data = pd.read_csv("kullanici_etkilesim_veri.csv")

# Kolon bilgileri ve eksik değerler
data.info()

# Eksik değer sayısı
data.isnull().sum()

# Gereksiz boşlukları temizleme, eksik verileri düşürme
data = data.dropna()

# Kaydetme
data.to_pickle("hazirlanmis_etkilesim.pkl")

# İlk 5 satıra göz atalım
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186775 entries, 0 to 186774
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   uye_id          186775 non-null  int64
 1   urun_id         186775 non-null  int64
 2   eklenme_tarihi  186775 non-null  object
 3   puan            186775 non-null  int64
 4   event_type      186775 non-null  object
dtypes: int64(3), object(2)
memory usage: 7.1+ MB

    uye_id  urun_id           eklenme_tarihi  puan   event_type
0        0    72176  2024-08-05 05:43:02.000     1         view
1        0    67714  2024-08-05 05:45:51.000     5     purchase
2        0    66060  2024-08-05 05:53:56.000     4  add_to_cart
3  1659156    60388  2024-08-05 06:01:07.000     1         view
4        0    41669  2024-08-05 06:04:45.000     5     purchase

In [10]:

# Veri setini oku
data = pd.read_csv("kullanici_satin_alma_veri.csv")

# Kolon bilgileri ve eksik değerler
data.info()

# Eksik değer sayısı
data.isnull().sum()

# Gereksiz boşlukları temizleme, eksik verileri düşürme
data = data.dropna()

# Kaydetme
data.to_pickle("hazirlanmis_satin_alma.pkl")

# İlk 5 satıra göz atalım
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_ID     1000 non-null   int64
 1   Product_ID  1000 non-null   int64
 2   Quantity    1000 non-null   int64
 3   Timestamp   1000 non-null   object
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

   User_ID  Product_ID  Quantity            Timestamp
0       76       67785         4  2024-02-28 15:46:28
1       62       44238         5  2024-03-03 03:48:28
2       99       38560         3  2024-08-03 20:02:49
3       67       48066         1  2024-08-08 04:40:07
4       93       25530         1  2024-06-12 00:33:24

In [1]:
import pandas as pd

# Doğru ayraçla CSV dosyasını yükleyelim
data = pd.read_csv("urun_ozellikleri.csv", sep=";")

# Sütun bilgilerini kontrol edelim
print(data.info())

# Eksik veri var mı kontrol edelim
print(data.isnull().sum())

# "Unnamed" sütunlarını kaldırma
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]

# 'ozellikleri' sütunu boş olan satırları kaldır
data = data.dropna(subset=['ozellikleri'])

# Kaydetme
data.to_pickle("hazirlanmis_urun_ozellikleri.pkl")

# İlk 5 satıra göz atalım
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23387 entries, 0 to 23386
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   urun_id      23387 non-null  int64
 1   adi          23387 non-null  object
 2   marka_id     23375 non-null  object
 3   kategori_id  23387 non-null  object
 4   ozellikleri  23386 non-null  object
dtypes: int64(1), object(4)
memory usage: 913.7+ KB
None
urun_id         0
adi             0
marka_id       12
kategori_id     0
ozellikleri     1
dtype: int64

,urun_id,adi,marka_id,kategori_id,ozellikleri
0,16328,MSI PRO B650M-B DDR5 AMD B650 AM5 Soket DDR5 6...,75,779,"AM5, AMD, AMD B650, 2 x USB 2.0, 4 x USB 2.0, ..."
1,90137,MSI Modern 15 F13MG-098XTR i7-1355U 16GB DDR4 ...,75,834,"Intel Core i7-1355U, 3.70GHz, INTEL Core™ i7, ..."
2,25777,Sony DualSense Siyah Kablosuz PS5 Oyun Kolu (İ...,107,1426,"Siyah, Gamepad, PS5"
3,91026,Sony DualSense Beyaz Kablosuz PS5 Oyun Kolu (İ...,107,1426,"Beyaz, Gamepad, PS5"
4,11443,Sony PlayStation 5 Slim Digital Sürüm Oyun Kon...,107,850,"1TB, İthalatçı, Playstation 5, Slim"

In [2]:
import pandas as pd

# 1. CSV'leri oku
etkilesim_df = pd.read_csv("kullanici_etkilesim_veri.csv")
urun_df = pd.read_csv("urun_ozellikleri.csv", delimiter=";")


# 2. "Unnamed" sütunlarını kaldır
etkilesim_df = etkilesim_df.loc[:, ~etkilesim_df.columns.str.contains('^Unnamed')]
urun_df = urun_df.loc[:, ~urun_df.columns.str.contains('^Unnamed')]

# 3. 'ozellikleri' sütunu boş olan satırları kaldır
urun_df = urun_df.dropna(subset=['ozellikleri'])

# 4. Birleştirme işlemi (urun_id üzerinden)
etkilesim_df['urun_id'] = etkilesim_df['urun_id'].astype(int)
urun_df['urun_id'] = urun_df['urun_id'].astype(int)
birlesik_df = pd.merge(etkilesim_df, urun_df, on='urun_id', how='left')

# 5. .pkl dosyasına kaydet
birlesik_df.to_pickle("birlesik_veri.pkl")

In [4]:
import pandas as pd

# 1. CSV dosyalarını oku
etkilesim_df = pd.read_csv("kullanici_etkilesim_veri.csv")
urun_df = pd.read_csv("urun_ozellikleri.csv", delimiter=";")

# 2. "Unnamed" (gereksiz index) sütunlarını kaldır
etkilesim_df = etkilesim_df.loc[:, ~etkilesim_df.columns.str.contains("^Unnamed")]
urun_df = urun_df.loc[:, ~urun_df.columns.str.contains("^Unnamed")]

# 3. 'ozellikleri' sütunu boş olan satırları kaldır
urun_df = urun_df.dropna(subset=['ozellikleri'])

# 4. 'urun_id' sütunlarını int'e çevir (tip uyumu için)
etkilesim_df['urun_id'] = etkilesim_df['urun_id'].astype(int)
urun_df['urun_id'] = urun_df['urun_id'].astype(int)

# 5. Sadece eşleşen urun_id’ler ile INNER JOIN yap
birlesik_df = pd.merge(etkilesim_df, urun_df, on="urun_id", how="inner")

# 6. Her urun_id için yalnızca bir satır tut (ilkini al)
birlesik_df = birlesik_df.drop_duplicates(subset='urun_id', keep='first')

# 7. Sonucu pkl dosyasına kaydet
birlesik_df.to_pickle("birlesik_veri_tekil.pkl")